{"uuid": "36e14494-3fd6-4c90-a34a-fa4d3413750d", "children": ["61059d5d-5eab-45a9-ac6b-2e53af722b32", "cc2faaf4-a5fd-446d-8e6e-1022c38c73c6", "dcdf34b0-9abd-4021-a325-f04aae248312", "e4076d6e-898e-4cc7-b6c5-7e8b92d97676", "98e25ea9-6b91-44e6-8e1b-dcfb0facb01b", "7980c963-de83-4f5f-9851-2b5af16d0896", "ff93eec2-075c-45cb-9d31-b80afcd92c7d", "78851356-6550-4520-a85c-ffbf95076eb7", "f3cb3421-782b-49bf-91a5-4234452a7e47", "665b503d-1c97-4480-873b-803fb0292095"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n#0 0x5601d1d17ffa <unknown>\n#1 0x5601d17d6970 <unknown>\n#2 0x5601d1816711 <unknown>\n#3 0x5601d181129a <unknown>\n#4 0x5601d180c18f <unknown>\n#5 0x5601d185cbd9 <unknown>\n#6 0x5601d185c106 <unknown>\n#7 0x5601d184e063 <unknown>\n#8 0x5601d181a328 <unknown>\n#9 0x5601d181b491 <unknown>\n#10 0x5601d1cdf42b <unknown>\n#11 0x5601d1ce32ec <unknown>\n#12 0x5601d1cc6a22 <unknown>\n#13 0x5601d1ce3e64 <unknown>\n#14 0x5601d1caabef <unknown>\n#15 0x5601d1d06558 <unknown>\n#16 0x5601d1d06736 <unknown>\n#17 0x5601d1d16e76 <unknown>\n#18 0x7f810329caa4 <unknown>\n#19 0x7f8103329c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 24, in driver\n    driver = webdriver.Chrome(service=service_obj,options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 329, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742958864062, "stop": 1742958864220}], "start": 1742958864062, "stop": 1742958864638}