{"uuid": "66f3db0f-eed9-4b0c-9317-a0802024b95f", "children": ["e22140b7-47cd-4163-aa0e-5bf75fb3910f"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//input[@id='gnb_search']\"}\n  (Session info: chrome=134.0.6998.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x5594db7cfffa <unknown>\n#1 0x5594db28e970 <unknown>\n#2 0x5594db2e0385 <unknown>\n#3 0x5594db2e05b1 <unknown>\n#4 0x5594db32f3c4 <unknown>\n#5 0x5594db3062bd <unknown>\n#6 0x5594db32c70c <unknown>\n#7 0x5594db306063 <unknown>\n#8 0x5594db2d2328 <unknown>\n#9 0x5594db2d3491 <unknown>\n#10 0x5594db79742b <unknown>\n#11 0x5594db79b2ec <unknown>\n#12 0x5594db77ea22 <unknown>\n#13 0x5594db79be64 <unknown>\n#14 0x5594db762bef <unknown>\n#15 0x5594db7be558 <unknown>\n#16 0x5594db7be736 <unknown>\n#17 0x5594db7cee76 <unknown>\n#18 0x7fa03749caa4 <unknown>\n#19 0x7fa037529c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 28, in driver\n    driver.find_element(By.XPATH,\"//input[@id='gnb_search']\").click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742979520142, "stop": 1742979534012}], "start": 1742979520142, "stop": 1742979534091}