{"uuid": "925788f9-2095-4650-97b6-183ffe9b1060", "children": ["3a5bf19b-f993-459b-b891-6064d595fb8b", "65c8caaa-0716-4b2b-b53a-9e057bd4db5f", "f1af47de-4011-4363-846f-ee43c3992877", "4b553db3-f533-4be6-9c8e-9628976eeaf7", "4ff6345e-9efc-46e4-921f-c51f7f60beb1", "57ae6a94-805a-4658-a58f-fc06e2dc7ec8", "b423f2f2-8de5-4e82-a22a-92e96a15594f", "b5f531c3-b568-4aca-b1ad-3a37e6c5c559", "0ff27934-b919-4728-a4a3-969c4bb098aa", "03b33c43-9bd6-462f-b1dd-6d945f5dc65b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n#0 0x55e099602ffa <unknown>\n#1 0x55e0990c1970 <unknown>\n#2 0x55e099101711 <unknown>\n#3 0x55e0990fc29a <unknown>\n#4 0x55e0990f718f <unknown>\n#5 0x55e099147bd9 <unknown>\n#6 0x55e099147106 <unknown>\n#7 0x55e099139063 <unknown>\n#8 0x55e099105328 <unknown>\n#9 0x55e099106491 <unknown>\n#10 0x55e0995ca42b <unknown>\n#11 0x55e0995ce2ec <unknown>\n#12 0x55e0995b1a22 <unknown>\n#13 0x55e0995cee64 <unknown>\n#14 0x55e099595bef <unknown>\n#15 0x55e0995f1558 <unknown>\n#16 0x55e0995f1736 <unknown>\n#17 0x55e099601e76 <unknown>\n#18 0x7f6f1489caa4 <unknown>\n#19 0x7f6f14929c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 23, in driver\n    driver = webdriver.Chrome(service=service_obj,options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 329, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1743197356517, "stop": 1743197356708}], "start": 1743197356517, "stop": 1743197357123}