{"uuid": "dcb403f6-ee67-4c7c-95e5-a049136b85b3", "children": ["fb0bc296-83e4-4dac-af86-6ae3ec1df6ad", "8b0acbdc-1d51-4cb8-a94f-00f6f3d94415", "1eb3929d-0810-4d8c-94b6-807d4b43bce2", "ff3bdf56-6faa-40b5-8aed-fe69e5634c25", "e2839162-fab6-4635-a245-7e34d804b53d", "06459bc6-3fbd-4a75-b6f3-5c73687ff1b3", "b92cf3ae-b20a-41f1-a240-ba8c4dd2ff6d", "d8d59db4-b2f0-4fe9-9ba5-a249ce0faabc", "6f1eb715-5b1c-4621-af80-fb9973d33db8", "6e2a5bdb-80ff-4af9-984b-2058f58a34a4"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n#0 0x55ef7c72fffa <unknown>\n#1 0x55ef7c1ee970 <unknown>\n#2 0x55ef7c22e711 <unknown>\n#3 0x55ef7c22929a <unknown>\n#4 0x55ef7c22418f <unknown>\n#5 0x55ef7c274bd9 <unknown>\n#6 0x55ef7c274106 <unknown>\n#7 0x55ef7c266063 <unknown>\n#8 0x55ef7c232328 <unknown>\n#9 0x55ef7c233491 <unknown>\n#10 0x55ef7c6f742b <unknown>\n#11 0x55ef7c6fb2ec <unknown>\n#12 0x55ef7c6dea22 <unknown>\n#13 0x55ef7c6fbe64 <unknown>\n#14 0x55ef7c6c2bef <unknown>\n#15 0x55ef7c71e558 <unknown>\n#16 0x55ef7c71e736 <unknown>\n#17 0x55ef7c72ee76 <unknown>\n#18 0x7f707f49caa4 <unknown>\n#19 0x7f707f529c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=service_obj,options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 329, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742980779588, "stop": 1742980779754}], "start": 1742980779588, "stop": 1742980780187}