{"uuid": "ba7eec73-933d-456b-a53b-4e2c10445efa", "children": ["0277237c-84fe-4b01-889a-c478df44e8ec", "2b66f576-14b4-43ae-bb37-eaa7d5d0fcdc", "1d6a34b6-4452-4163-94d3-ad0d27ae3227", "81f930f8-f178-419b-b61d-41866ef8bc39", "048712a5-48b5-4104-8ce1-7257e444387a", "72dd8c97-4240-4cdf-9cb3-3c49b7d0b25c", "24fbf912-a208-4648-9da0-7f4016e9d6cb", "b4de7dd3-66b8-44ab-b305-32d221b5666c", "8a49eaec-e8d4-4cb5-9678-e9404f31aaba", "1e456d39-b405-41e8-85e4-90332c600f64"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n#0 0x55c6c02e4ffa <unknown>\n#1 0x55c6bfda3970 <unknown>\n#2 0x55c6bfde3711 <unknown>\n#3 0x55c6bfdde29a <unknown>\n#4 0x55c6bfdd918f <unknown>\n#5 0x55c6bfe29bd9 <unknown>\n#6 0x55c6bfe29106 <unknown>\n#7 0x55c6bfe1b063 <unknown>\n#8 0x55c6bfde7328 <unknown>\n#9 0x55c6bfde8491 <unknown>\n#10 0x55c6c02ac42b <unknown>\n#11 0x55c6c02b02ec <unknown>\n#12 0x55c6c0293a22 <unknown>\n#13 0x55c6c02b0e64 <unknown>\n#14 0x55c6c0277bef <unknown>\n#15 0x55c6c02d3558 <unknown>\n#16 0x55c6c02d3736 <unknown>\n#17 0x55c6c02e3e76 <unknown>\n#18 0x7f589ac9caa4 <unknown>\n#19 0x7f589ad29c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 27, in driver\n    driver = webdriver.Chrome(service=service_obj,options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 329, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1743026535724, "stop": 1743026535890}], "start": 1743026535724, "stop": 1743026536296}