{"uuid": "6e3233a2-3d2a-4d55-bf89-c7e2169bd55c", "children": ["5849efc5-c523-43ff-9512-886461d62855", "f38834f8-beb3-473a-b366-58d12be81820", "a97a8e89-7d64-4a50-bbe4-2efff87b99ae", "a0855fff-cd24-44ab-94fd-e2da786d53ca", "416935dc-b27e-4ade-86cb-2fabf03a6885", "af24283f-77ab-4cef-b3fc-3eda00c973c9", "f9c272a9-ef2a-48b1-a21c-2c2c6484310a", "ac9ab773-dcfe-4603-ac62-183e7863fd51", "c30f352a-6797-44ed-aeb5-9277ea8e3c2e", "a68c1992-e721-41cd-8d1e-d1da9f1d4c1b"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n#0 0x55819b436ffa <unknown>\n#1 0x55819aef5970 <unknown>\n#2 0x55819af35711 <unknown>\n#3 0x55819af3029a <unknown>\n#4 0x55819af2b18f <unknown>\n#5 0x55819af7bbd9 <unknown>\n#6 0x55819af7b106 <unknown>\n#7 0x55819af6d063 <unknown>\n#8 0x55819af39328 <unknown>\n#9 0x55819af3a491 <unknown>\n#10 0x55819b3fe42b <unknown>\n#11 0x55819b4022ec <unknown>\n#12 0x55819b3e5a22 <unknown>\n#13 0x55819b402e64 <unknown>\n#14 0x55819b3c9bef <unknown>\n#15 0x55819b425558 <unknown>\n#16 0x55819b425736 <unknown>\n#17 0x55819b435e76 <unknown>\n#18 0x7f70ea49caa4 <unknown>\n#19 0x7f70ea529c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/ui_tests/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=service_obj,options=chrome_options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 241, in __init__\n    self.start_session(capabilities)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 329, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742979536180, "stop": 1742979536386}], "start": 1742979536180, "stop": 1742979536818}