{"uuid": "7bd9f150-f97c-4d95-946a-99371ec3d5b2", "children": ["fa48e65c-4344-4946-9ae3-e14c8665a218", "e33387b3-fc1c-481d-bdbe-4085a9c7b44c", "2610af96-62ec-449e-ad36-2398a3aa1a3d", "037df2ea-3c7e-48cc-bb9f-69fa07ed0ddb", "3e02b9ae-dd6e-459d-94aa-71fba15e24de", "63f0d4d5-4662-4a32-abf1-4c0972e395b1", "4de49937-fbad-42e0-a7fd-21f0c545a8e9", "6306a8a9-76ef-4f86-b71b-8d6435690b45", "575bc0b2-89e4-4601-96cd-aeca2f9e01ea", "da74cd78-b53e-4705-bad8-1e4060931a10"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x55f296fbbffa <unknown>\n#1 0x55f296a7a970 <unknown>\n#2 0x55f296acc385 <unknown>\n#3 0x55f296acc5b1 <unknown>\n#4 0x55f296b1b3c4 <unknown>\n#5 0x55f296af22bd <unknown>\n#6 0x55f296b1870c <unknown>\n#7 0x55f296af2063 <unknown>\n#8 0x55f296abe328 <unknown>\n#9 0x55f296abf491 <unknown>\n#10 0x55f296f8342b <unknown>\n#11 0x55f296f872ec <unknown>\n#12 0x55f296f6aa22 <unknown>\n#13 0x55f296f87e64 <unknown>\n#14 0x55f296f4ebef <unknown>\n#15 0x55f296faa558 <unknown>\n#16 0x55f296faa736 <unknown>\n#17 0x55f296fbae76 <unknown>\n#18 0x7fb1fb69caa4 <unknown>\n#19 0x7fb1fb729c3c <unknown>\n\n", "trace": "  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QATEST/QATEST/src/tests/conftest.py\", line 37, in driver\n    WebDriverWait(driver, 10).until(\n  File \"/home/runner/work/QATEST/QATEST/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1743026918373, "stop": 1743026931358}], "start": 1743026918373, "stop": 1743026931414}